server:
  port: 8000
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1573037436/microservicecloud-config.git
