server:
  port: 6001
spring:
  application:
    name: microservice-consumer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
    instance:
      instance-id: microservicecloud-consumer6001 #只显示实例名，不显示机器名
      prefer-ip-address: true                     #访问路径可以显示IP地址
